#page title
page_title                                : Divinations                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Divinations & Astrology                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Thousands of people trust one of the best divination application. This original application for those who need to make a decision and need some help. You will receive actual, individual divinations that cannot be found in any other place. This app will help you to understand what is actually happening in your personal life, relationships and work.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                                 
email_address                             : hello@taro-app.ru
facebook_username                         :                                           
instagram_username                        : tarot_app
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Card of the day
    description                           : Simple and convenient divination allows you to quickly find out what does the upcoming day preparing for you.
    fontawesome_icon_name                 : magic
    
  - title                                 : Love and relationships, future, Celtic cross
    description                           : Choose the fortune-telling you need right now. A detailed description of each fortune telling, the value of the positions - will help you to easily choose the right one.
    fontawesome_icon_name                 : mobile

  - title                                 : Unique cards
    description                           : 72 author’s card, each of which is drawn specifically for the Tarot application. Each of the cards was created by one author.
    fontawesome_icon_name                 : play-circle

  - title                                 : New fortune telling every week
    description                           : Divination for a week or a month. Divination on two cards. Lots of new and interesting divinations every week.
    fontawesome_icon_name                 : sync

  - title                                 : Updates
    description                           : Constant updates and new features. In the near future- share fortune telling with friends and watch them.
    fontawesome_icon_name                 : adjust


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman